controllers/AccessController.php
<?php

namespace app\controllers;

use app\controllers\common\BaseController;
use app\models\Access;

class AccessController extends BaseController {

	//权限列表
    public function actionIndex(){
		$access_list = Access::find()->where([ 'status' => 1 ])->orderBy([ 'id' => SORT_DESC ])->all();
		return $this->render('index',[
			'list' => $access_list
		]);
    }

	/*
	 * 添加或者编辑权限
	 * get 展示页面
	 * post 处理添加或者编辑权限
	 */
    public function actionSet(){
		//如果是get请求则演示页面
		if( \Yii::$app->request->isGet ){
			$id = $this->get("id",0);
			$info = [];
			if( $id ){
				$info = Access::find()->where([ 'status' => 1 ,'id' => $id ])->one();
			}
			return $this->render('set',[
				'info' => $info
			]);
		}

		$id = intval( $this->post("id",0) );
		$title = trim( $this->post("title","") );
		$urls = trim( $this->post("urls","") );
		$date_now = date("Y-m-d H:i:s");
		if( mb_strlen($title,"utf-8") < 1 || mb_strlen($title,"utf-8") > 20 ){
			return $this->renderJSON([],'请输入合法的权限标题~~',-1);
		}

		if( !$urls ){
			return $this->renderJSON([],'请输入合法的Urls~~',-1);
		}

		$urls = explode("\n",$urls);
		if( !$urls ){
			return $this->renderJSON([],'请输入合法的Urls~~',-1);
		}

		//查询同一标题的是否存在
		$has_in = Access::find()->where([ 'title' => $title ])->andWhere([ '!=','id',$id ])->count();
		if( $has_in ){
			return $this->renderJSON([],'该权限标题已存在~~',-1);
		}

		//查询指定id的权限
		$info = Access::find()->where([ 'id' => $id ])->one();
		if( $info ){//如果存在则是编辑
			$model_access = $info;
		}else{//不存在就是添加
			$model_access = new Access();
			$model_access->status = 1;
			$model_access->created_time =  $date_now;
		}
		$model_access->title = $title;
		$model_access->urls = json_encode( $urls );//json格式保存的
		$model_access->updated_time = $date_now;
		$model_access->save(0);

		return $this->renderJSON([],'操作成功~~');
	}
}

views/access/index.php
<?php
use \app\services\DataHelper;
use \app\services\UrlService;
?>
<div class="row">
	<div class="col-xs-9 col-sm-9 col-md-9  col-lg-9">
		<h5>权限列表</h5>
	</div>
	<div class="col-xs-3 col-sm-3 col-md-3  col-lg-3">
		<a href="<?=UrlService::buildUrl("/access/set");?>" class="btn btn-link pull-right">添加权限</a>
	</div>
</div>
<hr/>
<div class="table-responsive">
	<table class="table table-bordered">
		<thead>
		<tr>
			<th>权限</th>
			<th>Urls</th>
			<th>操作</th>
		</tr>
		</thead>
		<tbody>
		<?php if( $list ):?>
			<?php foreach( $list as $_key => $_access_info ):?>
				<?php
					$tmp_urls = @json_decode( $_access_info['urls'],true );
					$tmp_urls = $tmp_urls?$tmp_urls:[];
				?>
				<tr>
					<td><?=$_access_info['title'];?></td>
					<td><?=implode("<br/>",$tmp_urls);?></td>
					<td>
						<a href="<?=UrlService::buildUrl("/access/set",[ 'id' => $_access_info['id'] ]);?>" class="btn btn-link">编辑</a>
					</td>
				</tr>
			<?php endforeach;?>
		<?php else:?>
			<tr> <td colspan="3">暂无权限</td> </tr>
		<?php endif;?>
		</tbody>
	</table>
</div>

views/access/set.php
<?php
use \app\services\DataHelper;
use \app\services\UrlService;
use \app\services\StaticService;
StaticService::includeAppJsStatic("/js/access/set.js",\app\assets\AppAsset::className());
?>
<div class="row">
	<div class="col-xs-9 col-sm-9 col-md-9  col-lg-9">
		<h5>新增权限</h5>
	</div>
</div>
<hr/>
<div class="row">
	<div class="form-horizontal access_set_wrap" role="form">
		<div class="form-group">
			<label class="col-xs-2 col-sm-2 col-md-2 col-lg-2 control-label">权限标题</label>
			<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
				<input type="text" class="form-control" name="title" placeholder="请输入权限标题" value="<?=$info?$info['title']:'';?>">
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 col-sm-2 col-md-2 col-lg-2 control-label">Urls</label>
			<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <?php
				    $urls = $info?@json_decode( $info['urls'],true ):[];
				    $urls = $urls?$urls:[];
                ?>
                <textarea class="form-control" rows="5" placeholder="一行一个url" name="urls"><?=implode("\r\n",$urls);?></textarea>
			</div>
		</div>
		<div class="col-xs-6 col-xs-offset-2 col-sm-6 col-sm-offset-2 col-md-6  col-md-offset-2 col-lg-6 col-sm-lg-2 ">
            <input type="hidden" name="id"  value="<?=$info?$info['id']:0;?>">
			<button type="button" class="btn btn-primary pull-right  save">确定</button>
		</div>
	</div>
</div>