models/Role.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "role".
 *
 * @property integer $id
 * @property string $name
 * @property integer $status
 * @property string $updated_time
 * @property string $created_time
 */
class Role extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'role';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status'], 'integer'],
            [['updated_time', 'created_time'], 'safe'],
            [['name'], 'string', 'max' => 50],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'status' => 'Status',
            'updated_time' => 'Updated Time',
            'created_time' => 'Created Time',
        ];
    }
}

controllers/RoleController.php
<?php
/**
 * Class RoleController
 */

namespace app\controllers;


use app\controllers\common\BaseController;
use app\models\Access;
use app\models\Role;
use app\models\RoleAccess;
use app\services\UrlService;

class RoleController extends  BaseController {
	//角色列表页面
	public function actionIndex(){
		$list = Role::find()->orderBy([ 'id' => SORT_DESC ])->all();

		return $this->render("index",[
			'list' => $list
		]);
	}

	public function actionAdd(){

	}

	public function actionEdit(){

	}
	/*
	 * 添加或者编辑角色页面
	 * get 展示页面
	 * post 处理添加或者编辑动作
	 */
	public function actionSet(){
		if( \Yii::$app->request->isGet ){
			$id = $this->get("id",0);
			$info = [];
			if( $id ){
				$info = Role::find()->where([ 'id' => $id ])->one();
			}
			return $this->render("set",[
				"info" => $info
			]);
		}

		$id = $this->post("id",0);
		$name = $this->post("name","");
		$date_now = date("Y-m-d H:i:s");
		if( !$name ){
			return $this->renderJSON([],"请输入合法的角色名称~~",-1);
		}
		//查询是否存在角色名相等的记录
		$role_info = Role::find()
			->where([ 'name' => $name ])->andWhere([ '!=','id',$id ])
			->one();
		if( $role_info ){
			return $this->renderJSON([],"该角色名称已存在，请输入其他的角色名称~~",-1);
		}

		$info = Role::find()->where([ 'id' => $id ])->one();
		if( $info ){//编辑动作
			$role_model = $info;
		}else{//添加动作
			$role_model = new Role();
			$role_model->created_time = $date_now;
		}
		$role_model->name = $name;
		$role_model->updated_time = $date_now;

		$role_model->save(0);
		return $this->renderJSON([],"操作成功~~",200);
	}

	//设置角色和权限的关系逻辑
	public function actionAccess(){
		//http get 请求 展示页面
		if( \Yii::$app->request->isGet ){
			$id = $this->get("id",0);
			$reback_url =  UrlService::buildUrl("/role/index");
			if( !$id ){
				return $this->redirect( $reback_url );
			}
			$info = Role::find()->where([ 'id' => $id ])->one();
			if( !$info ){
				return $this->redirect( $reback_url );
			}

			//取出所有的权限
			$access_list = Access::find()->where([ 'status' => 1 ])->orderBy( [ 'id' => SORT_DESC ])->all();

			//取出所有已分配的权限
			$role_access_list = RoleAccess::find()->where([ 'role_id' => $id ])->asArray()->all();
			$access_ids = array_column( $role_access_list,"access_id" );
			return $this->render("access",[
				"info" => $info,
				'access_list' => $access_list,
				"access_ids" => $access_ids
			]);
		}
		//实现保存选中权限的逻辑
		$id = $this->post("id",0);
		$access_ids = $this->post("access_ids",[]);

		if( !$id ){
			return $this->renderJSON([],"您指定的角色不存在",-1);
		}

		$info = Role::find()->where([ 'id' => $id ])->one();
		if( !$info ){
			return $this->renderJSON([],"您指定的角色不存在",-1);
		}

		//取出所有已分配给指定角色的权限
		$role_access_list = RoleAccess::find()->where([ 'role_id' => $id ])->asArray()->all();
		$assign_access_ids = array_column( $role_access_list,'access_id' );
		/**
		 * 找出删除的权限
		 * 假如已有的权限集合是A，界面传递过得权限集合是B
		 * 权限集合A当中的某个权限不在权限集合B当中，就应该删除
		 * 使用 array_diff() 计算补集
		 */
		$delete_access_ids = array_diff( $assign_access_ids,$access_ids );
		if( $delete_access_ids ){
			RoleAccess::deleteAll([ 'role_id' => $id,'access_id' => $delete_access_ids ]);
		}

		/**
		 * 找出添加的权限
		 * 假如已有的权限集合是A，界面传递过得权限集合是B
		 * 权限集合B当中的某个权限不在权限集合A当中，就应该添加
		 * 使用 array_diff() 计算补集
		 */
		$new_access_ids = array_diff( $access_ids,$assign_access_ids );
		if( $new_access_ids ){
			foreach( $new_access_ids as $_access_id  ){
				$tmp_model_role_access = new RoleAccess();
				$tmp_model_role_access->role_id = $id;
				$tmp_model_role_access->access_id = $_access_id;
				$tmp_model_role_access->created_time = date("Y-m-d H:i:s");
				$tmp_model_role_access->save( 0 );
			}
		}
		return $this->renderJSON([],"操作成功~~",200 );
	}
}

views/role/access.php
<?php
use \app\services\StaticService;
StaticService::includeAppJsStatic("/js/role/access.js",\app\assets\AppAsset::className());
?>
<div class="row">
	<div class="col-xs-9 col-sm-9 col-md-9  col-lg-9">
		<h5>为 <?=$info["name"];?> 设置权限</h5>
	</div>
</div>
<hr/>
<div class="row">
	<div class="form-horizontal role_access_set_wrap" role="form">
        <div class="form-group">
            <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
                <?php if( $access_list ):?>
                    <?php foreach( $access_list as $_item ):?>
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="access_ids[]" value="<?=$_item['id'];?>"
                                <?php if( in_array( $_item['id'],$access_ids ) ):?> checked <?php endif;?>
                                >
                                <?=$_item['title'];?>
                            </label>
                        </div>
                    <?php endforeach;?>
                <?php endif;?>
            </div>
        </div>
		<div class="col-xs-6 col-xs-offset-2 col-sm-6 col-sm-offset-2 col-md-6  col-md-offset-2 col-lg-6 col-sm-lg-2 ">
            <input type="hidden" name="id" value="<?=$info['id'];?>">
			<button type="button" class="btn btn-primary pull-right  save">确定</button>
		</div>
	</div>
</div>

views/role/index.php
<?php
use \app\services\DataHelper;
use \app\services\UrlService;
?>
<div class="row">
	<div class="col-xs-9 col-sm-9 col-md-9  col-lg-9">
		<h5>角色列表</h5>
	</div>
	<div class="col-xs-3 col-sm-3 col-md-3  col-lg-3">
		<a href="<?=UrlService::buildUrl("/role/set");?>" class="btn btn-link pull-right">添加角色</a>
	</div>
</div>
<hr/>
<div class="table-responsive">
	<table class="table table-bordered">
		<thead>
		<tr>
			<th>角色</th>
			<th>操作</th>
		</tr>
		</thead>
		<tbody>
            <?php if( $list ):?>
                <?php foreach( $list as $_item ):?>
                    <tr>
                        <td><?=$_item['name'];?></td>
                        <td>
                            <a href="<?=UrlService::buildUrl("/role/set",[ 'id' => $_item['id'] ]);?>">编辑</a>
                            <a href="<?=UrlService::buildUrl("/role/access",[ 'id' => $_item['id'] ]);?>">设置权限</a>
                        </td>
                    </tr>
                <?php endforeach;?>
            <?php else:?>
                <tr><td colspan="2">暂无数据</td></tr>
            <?php endif;?>
		</tbody>
	</table>
</div>

views/role/set.php
<?php
use \app\services\DataHelper;
use \app\services\UrlService;
use \app\services\StaticService;
//Yii::$app->getView()->registerJs("/js/role/set.js",\app\assets\AppAsset::className() );
StaticService::includeAppJsStatic( "/js/role/set.js",\app\assets\AppAsset::className() );
?>
<div class="row">
	<div class="col-xs-9 col-sm-9 col-md-9  col-lg-9">
		<h5>新增角色</h5>
	</div>
</div>
<hr/>
<div class="row">
	<div class="form-horizontal role_set_wrap" role="form">
		<div class="form-group">
			<label class="col-xs-2 col-sm-2 col-md-2 col-lg-2 control-label">角色</label>
			<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
				<input type="text" class="form-control" name="name" placeholder="请输入角色" value="<?=$info?$info['name']:'';?>">
			</div>
		</div>
		<div class="col-xs-6 col-xs-offset-2 col-sm-6 col-sm-offset-2 col-md-6  col-md-offset-2 col-lg-6 col-sm-lg-2 ">
            <input type="hidden" name="id" value="<?=$info?$info['id']:'';?>"/>
			<button type="button" class="btn btn-primary pull-right  save">确定</button>
		</div>
	</div>
</div>